[package]
name = "vkengine"
version = "0.1.0"
authors = ["Dennis Kristiansen <dennkris@live.no>"]
edition = "2018"

[dependencies]
winit = "0.18.0"
vulkano = "0.11.1"
vulkano-win = "0.11.0"
vulkano-shaders = "0.11.0"
#vulkano-shaders = { path = "../vulkano/vulkano-shaders" }
#vulkano-shader-derive = "0.10.0"
#vulkano = { path = "../vulkano/vulkano" }
#vulkano-shader-derive = { path = "../vulkano/vulkano-shader-derive" }
#vulkano-win = { path = "../vulkano/vulkano-win" }

float_duration = "0.3.3"
hibitset = "0.5.2"
log = "0.4.6"
env_logger = "0.6.0"

alga = "0.7.2"
nalgebra = "0.16.10"
#ncollide3d = "*"
#nphysics3d = "*"

#glft = "*"
genmesh = "0.6.2"

specs = "0.14.0"
specs-derive = "0.3.0"
specs-hierarchy = "0.3.0"

[profile.release]
lto = true
